// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gmd_fast_cpp
List gmd_fast_cpp(const arma::mat& X, const arma::sp_mat& Q, const arma::sp_mat& R, int k, double tol, int maxit, int seed);
RcppExport SEXP _genpca_gmd_fast_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp(X, Q, R, k, tol, maxit, seed));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_dn
Rcpp::List gmd_fast_cpp_dn(const arma::mat& X, const arma::mat& Q, const arma::mat& R, const int k, const double tol);
RcppExport SEXP _genpca_gmd_fast_cpp_dn(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_dn(X, Q, R, k, tol));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_sp
Rcpp::List gmd_fast_cpp_sp(const arma::mat& X, const arma::sp_mat& Q, const arma::sp_mat& R, const int k, const double tol);
RcppExport SEXP _genpca_gmd_fast_cpp_sp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_sp(X, Q, R, k, tol));
    return rcpp_result_gen;
END_RCPP
}
// gmd_deflation_cpp
List gmd_deflation_cpp(const arma::mat& X, arma::sp_mat Q, arma::sp_mat R, int k, double thr);
RcppExport SEXP _genpca_gmd_deflation_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_deflation_cpp(X, Q, R, k, thr));
    return rcpp_result_gen;
END_RCPP
}
// sgmd_deflation_cpp
List sgmd_deflation_cpp(const arma::sp_mat& X, arma::sp_mat Q, arma::sp_mat R, int k, double thr);
RcppExport SEXP _genpca_sgmd_deflation_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(sgmd_deflation_cpp(X, Q, R, k, thr));
    return rcpp_result_gen;
END_RCPP
}
// gmdLA_cpp
List gmdLA_cpp(const arma::mat& X, arma::sp_mat Q, arma::mat R, int k);
RcppExport SEXP _genpca_gmdLA_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(gmdLA_cpp(X, Q, R, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genpca_gmd_fast_cpp", (DL_FUNC) &_genpca_gmd_fast_cpp, 7},
    {"_genpca_gmd_fast_cpp_dn", (DL_FUNC) &_genpca_gmd_fast_cpp_dn, 5},
    {"_genpca_gmd_fast_cpp_sp", (DL_FUNC) &_genpca_gmd_fast_cpp_sp, 5},
    {"_genpca_gmd_deflation_cpp", (DL_FUNC) &_genpca_gmd_deflation_cpp, 5},
    {"_genpca_sgmd_deflation_cpp", (DL_FUNC) &_genpca_sgmd_deflation_cpp, 5},
    {"_genpca_gmdLA_cpp", (DL_FUNC) &_genpca_gmdLA_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_genpca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
