// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gmd_fast_cpp_dn
Rcpp::List gmd_fast_cpp_dn(const arma::mat& X, const arma::mat& Q, const arma::mat& R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_dn(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_dn(X, Q, R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_sp
Rcpp::List gmd_fast_cpp_sp(const arma::mat& X, const arma::sp_mat& Q, const arma::sp_mat& R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_sp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_sp(X, Q, R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_primal_dn
Rcpp::List gmd_fast_cpp_primal_dn(const arma::mat& X, const arma::mat& Q, const arma::mat& L_R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_primal_dn(SEXP XSEXP, SEXP QSEXP, SEXP L_RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L_R(L_RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_primal_dn(X, Q, L_R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_primal_sp
Rcpp::List gmd_fast_cpp_primal_sp(const arma::mat& X, const arma::sp_mat& Q, const arma::mat& L_R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_primal_sp(SEXP XSEXP, SEXP QSEXP, SEXP L_RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L_R(L_RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_primal_sp(X, Q, L_R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_dual_dn
Rcpp::List gmd_fast_cpp_dual_dn(const arma::mat& X, const arma::mat& L_Q, const arma::mat& R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_dual_dn(SEXP XSEXP, SEXP L_QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L_Q(L_QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_dual_dn(X, L_Q, R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_fast_cpp_dual_sp
Rcpp::List gmd_fast_cpp_dual_sp(const arma::mat& X, const arma::mat& L_Q, const arma::sp_mat& R, const int k, const double tol, const int maxit, const bool topk);
RcppExport SEXP _genpca_gmd_fast_cpp_dual_sp(SEXP XSEXP, SEXP L_QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP topkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L_Q(L_QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const bool >::type topk(topkSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_fast_cpp_dual_sp(X, L_Q, R, k, tol, maxit, topk));
    return rcpp_result_gen;
END_RCPP
}
// gmd_randomized_cpp_dn
Rcpp::List gmd_randomized_cpp_dn(const arma::mat& X, const arma::mat& Q, const arma::mat& R, const int k, const int oversample, const int n_power, const int n_polish, const double jitter, const double tol, const double polish_tol, const int seed);
RcppExport SEXP _genpca_gmd_randomized_cpp_dn(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP oversampleSEXP, SEXP n_powerSEXP, SEXP n_polishSEXP, SEXP jitterSEXP, SEXP tolSEXP, SEXP polish_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< const int >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< const int >::type n_polish(n_polishSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type polish_tol(polish_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_randomized_cpp_dn(X, Q, R, k, oversample, n_power, n_polish, jitter, tol, polish_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// gmd_randomized_cpp_sp
Rcpp::List gmd_randomized_cpp_sp(const arma::mat& X, const arma::sp_mat& Q, const arma::sp_mat& R, const int k, const int oversample, const int n_power, const int n_polish, const double jitter, const double tol, const double polish_tol, const int seed);
RcppExport SEXP _genpca_gmd_randomized_cpp_sp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP oversampleSEXP, SEXP n_powerSEXP, SEXP n_polishSEXP, SEXP jitterSEXP, SEXP tolSEXP, SEXP polish_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< const int >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< const int >::type n_polish(n_polishSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type polish_tol(polish_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_randomized_cpp_sp(X, Q, R, k, oversample, n_power, n_polish, jitter, tol, polish_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// gmd_randomized_cpp_qsp_rdn
Rcpp::List gmd_randomized_cpp_qsp_rdn(const arma::mat& X, const arma::sp_mat& Q, const arma::mat& R, const int k, const int oversample, const int n_power, const int n_polish, const double jitter, const double tol, const double polish_tol, const int seed);
RcppExport SEXP _genpca_gmd_randomized_cpp_qsp_rdn(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP oversampleSEXP, SEXP n_powerSEXP, SEXP n_polishSEXP, SEXP jitterSEXP, SEXP tolSEXP, SEXP polish_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< const int >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< const int >::type n_polish(n_polishSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type polish_tol(polish_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_randomized_cpp_qsp_rdn(X, Q, R, k, oversample, n_power, n_polish, jitter, tol, polish_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// gmd_randomized_cpp_qdn_rsp
Rcpp::List gmd_randomized_cpp_qdn_rsp(const arma::mat& X, const arma::mat& Q, const arma::sp_mat& R, const int k, const int oversample, const int n_power, const int n_polish, const double jitter, const double tol, const double polish_tol, const int seed);
RcppExport SEXP _genpca_gmd_randomized_cpp_qdn_rsp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP oversampleSEXP, SEXP n_powerSEXP, SEXP n_polishSEXP, SEXP jitterSEXP, SEXP tolSEXP, SEXP polish_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< const int >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< const int >::type n_polish(n_polishSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type polish_tol(polish_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_randomized_cpp_qdn_rsp(X, Q, R, k, oversample, n_power, n_polish, jitter, tol, polish_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// gmd_deflation_cpp
List gmd_deflation_cpp(const arma::mat& X, arma::sp_mat Q, arma::sp_mat R, int k, double thr, int maxit, bool verbose);
RcppExport SEXP _genpca_gmd_deflation_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP thrSEXP, SEXP maxitSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(gmd_deflation_cpp(X, Q, R, k, thr, maxit, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sgmd_deflation_cpp
List sgmd_deflation_cpp(const arma::sp_mat& X, arma::sp_mat Q, arma::sp_mat R, int k, double thr, int maxit, bool verbose);
RcppExport SEXP _genpca_sgmd_deflation_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP, SEXP thrSEXP, SEXP maxitSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sgmd_deflation_cpp(X, Q, R, k, thr, maxit, verbose));
    return rcpp_result_gen;
END_RCPP
}
// gmdLA_cpp
List gmdLA_cpp(const arma::mat& X, arma::sp_mat Q, arma::mat R, int k);
RcppExport SEXP _genpca_gmdLA_cpp(SEXP XSEXP, SEXP QSEXP, SEXP RSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(gmdLA_cpp(X, Q, R, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genpca_gmd_fast_cpp_dn", (DL_FUNC) &_genpca_gmd_fast_cpp_dn, 7},
    {"_genpca_gmd_fast_cpp_sp", (DL_FUNC) &_genpca_gmd_fast_cpp_sp, 7},
    {"_genpca_gmd_fast_cpp_primal_dn", (DL_FUNC) &_genpca_gmd_fast_cpp_primal_dn, 7},
    {"_genpca_gmd_fast_cpp_primal_sp", (DL_FUNC) &_genpca_gmd_fast_cpp_primal_sp, 7},
    {"_genpca_gmd_fast_cpp_dual_dn", (DL_FUNC) &_genpca_gmd_fast_cpp_dual_dn, 7},
    {"_genpca_gmd_fast_cpp_dual_sp", (DL_FUNC) &_genpca_gmd_fast_cpp_dual_sp, 7},
    {"_genpca_gmd_randomized_cpp_dn", (DL_FUNC) &_genpca_gmd_randomized_cpp_dn, 11},
    {"_genpca_gmd_randomized_cpp_sp", (DL_FUNC) &_genpca_gmd_randomized_cpp_sp, 11},
    {"_genpca_gmd_randomized_cpp_qsp_rdn", (DL_FUNC) &_genpca_gmd_randomized_cpp_qsp_rdn, 11},
    {"_genpca_gmd_randomized_cpp_qdn_rsp", (DL_FUNC) &_genpca_gmd_randomized_cpp_qdn_rsp, 11},
    {"_genpca_gmd_deflation_cpp", (DL_FUNC) &_genpca_gmd_deflation_cpp, 7},
    {"_genpca_sgmd_deflation_cpp", (DL_FUNC) &_genpca_sgmd_deflation_cpp, 7},
    {"_genpca_gmdLA_cpp", (DL_FUNC) &_genpca_gmdLA_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_genpca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
