# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmd_fast_cpp_dn <- function(X, Q, R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_dn`, X, Q, R, k, tol, maxit, topk)
}

gmd_fast_cpp_sp <- function(X, Q, R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_sp`, X, Q, R, k, tol, maxit, topk)
}

gmd_fast_cpp_primal_dn <- function(X, Q, L_R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_primal_dn`, X, Q, L_R, k, tol, maxit, topk)
}

gmd_fast_cpp_primal_sp <- function(X, Q, L_R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_primal_sp`, X, Q, L_R, k, tol, maxit, topk)
}

gmd_fast_cpp_dual_dn <- function(X, L_Q, R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_dual_dn`, X, L_Q, R, k, tol, maxit, topk)
}

gmd_fast_cpp_dual_sp <- function(X, L_Q, R, k, tol = 1e-8, maxit = 1000L, topk = TRUE) {
    .Call(`_genpca_gmd_fast_cpp_dual_sp`, X, L_Q, R, k, tol, maxit, topk)
}

gmd_deflation_cpp <- function(X, Q, R, k, thr = 1e-7, maxit = 500L, verbose = FALSE) {
    .Call(`_genpca_gmd_deflation_cpp`, X, Q, R, k, thr, maxit, verbose)
}

sgmd_deflation_cpp <- function(X, Q, R, k, thr = 1e-5, maxit = 500L, verbose = FALSE) {
    .Call(`_genpca_sgmd_deflation_cpp`, X, Q, R, k, thr, maxit, verbose)
}

gmdLA_cpp <- function(X, Q, R, k) {
    .Call(`_genpca_gmdLA_cpp`, X, Q, R, k)
}

