# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmd_fast_cpp <- function(X, Q, R, k, tol = 1e-9, maxit = 1000L, seed = 1234L) {
    .Call(`_genpca_gmd_fast_cpp`, X, Q, R, k, tol, maxit, seed)
}

gmd_deflation_cpp <- function(X, Q, R, k, thr = 1e-7) {
    .Call(`_genpca_gmd_deflation_cpp`, X, Q, R, k, thr)
}

sgmd_deflation_cpp <- function(X, Q, R, k, thr = 1e-5) {
    .Call(`_genpca_sgmd_deflation_cpp`, X, Q, R, k, thr)
}

gmdLA_cpp <- function(X, Q, R, k) {
    .Call(`_genpca_gmdLA_cpp`, X, Q, R, k)
}

